export const RESPONSE_AUTH = 'RESPONSE_AUTH';
export const RESPONSE_VIP = 'RESPONSE_VIP';
export const SUCCESS_CREATE = 'SUCCESS_CREATE';
export const SUCCESS_DELETE = 'SUCCESS_DELETE';
export const ERROR_CREATE = 'ERROR_CREATE';
export const ERROR_UPDATE = 'ERROR_UPDATE';
export const PARTICIPATE = 'PARTICIPATE';
